class Titles:
    
    """
    Class containing titles of Wikipedia level 3 vital articles
    """
    
    """
    PEOPLE
    """
    
    LEADERS_AND_POLITICIANS = ['Hammurabi',
                                'Hatshepsut',
                                'Ramesses II',
                                'Cyrus the Great',
                                'Alexander the Great',
                                'Ashoka',
                                'Qin Shi Huang',
                                'Julius Caesar',
                                'Augustus',
                                'Charlemagne',
                                'Genghis Khan',
                                'Mansa Musa',
                                'Joan of Arc',
                                'Suleiman the Magnificent',
                                'Akbar',
                                'Elizabeth I',
                                'Catherine the Great',
                                'George Washington',
                                'Napoleon',
                                'Simón Bolívar',
                                'Abraham Lincoln',
                                'Mahatma Gandhi',
                                'Joseph Stalin',
                                'Adolf Hitler',
                                'Mao Zedong',
                                'Nelson Mandela']
    
    RELIGIOUS_FIGURES = ['Abraham',
                        'Moses',
                        'The Buddha',
                        'Jesus',
                        'Paul the Apostle',
                        'Muhammad',
                        'Adi Shankara',
                        'Martin Luther']
    
    EXPLORERS = ['Marco Polo',
                'Zheng He',
                'Christopher Columbus',
                'Vasco da Gama',
                'Ferdinand Magellan',
                'James Cook',
                'Roald Amundsen']
    
    PHILOSOPHERS_AND_SOCIAL_SCIENTISTS = ['Confucius',
                                        'Laozi',
                                        'Herodotus',
                                        'Socrates',
                                        'Plato',
                                        'Aristotle',
                                        'Cicero',
                                        'Thomas Aquinas',
                                        'Ibn Khaldun',
                                        'Niccolò Machiavelli',
                                        'René Descartes',
                                        'John Locke',
                                        'Adam Smith',
                                        'Immanuel Kant',
                                        'Mary Wollstonecraft',
                                        'Karl Marx',
                                        'Friedrich Nietzsche',
                                        'Sigmund Freud']
    
    WRITERS = ['Homer',
            'Virgil',
            'Li Bai',
            'Murasaki Shikibu',
            'Rumi',
            'Dante Alighieri',
            'Miguel de Cervantes',
            'William Shakespeare',
            'Voltaire',
            'Leo Tolstoy',
            'Rabindranath Tagore']
    
    ARTISTS = ['Leonardo da Vinci',
            'Michelangelo',
            'Rembrandt',
            'Hokusai',
            'Pablo Picasso',
            'Frida Kahlo']
    
    MUSICIANS_AND_COMPOSERS = ['Johann Sebastian Bach',
                'Wolfgang Amadeus Mozart',
                'Ludwig van Beethoven',
                'Louis Armstrong',
                'The Beatles',
                'Michael Jackson']
    
    SCIENTISTS_AND_INVENTORS = ['Hippocrates',
                                'Avicenna',
                                'Shen Kuo',
                                'Johannes Gutenberg',
                                'Nicolaus Copernicus',
                                'Galileo Galilei',
                                'Isaac Newton',
                                'Carl Linnaeus',
                                'Antoine Lavoisier',
                                'Michael Faraday',
                                'Charles Darwin',
                                'Florence Nightingale',
                                'Louis Pasteur',
                                'James Clerk Maxwell',
                                'Dmitri Mendeleev',
                                'Thomas Edison',
                                'Nikola Tesla',
                                'Marie Curie',
                                'Albert Einstein']
    
    MATHEMATICIANS = ['Archimedes',
                    'Euclid',
                    'Muhammad ibn Musa al-Khwarizmi',
                    'Leonhard Euler',
                    'Carl Friedrich Gauss',
                    'Emmy Noether',
                    'Kurt Gödel',
                    'Alan Turing']
    
    FILMMAKERS = ['Charlie Chaplin',
                    'Walt Disney'] 
    
    BUSINESS_PEOPLE = ['Henry Ford']
    
    """
    HISTORY
    """
    
    GENERAL_HISTORY = ['History ',
                    'Human history ',
                    'Civilization ',
                    'Archaeology']
    
    HISTORY_BY_REGION = ['History of Africa',
                        'History of Asia',
                        'History of East Asia',
                        'History of India',
                        'History of the Middle East',
                        'History of Europe',
                        'History of North America',
                        'History of Oceania',
                        'History of South America']
    
    HISTORY_BY_SUBJECT = ['History of science ',
                        'History of art ',
                        'History of agriculture',
                        'History of architecture',
                        'History of film',
                        'History of literature',
                        'History of mathematics',
                        'History of medicine',
                        'History of music',
                        'History of technology',
                        'Military history']
    
    PREHISTORY = ['Prehistory ',
                'Stone Age',
                'Early human migrations',
                'Neolithic Revolution']
    
    ANCIENT_HISTORY = ['Ancient history ',
                    'Bronze Age',
                    'Ancient Egypt',
                    'Indus Valley Civilisation',
                    'Mesopotamia',
                    'Sumer',
                    'Phoenicia',
                    'Iron Age',
                    'Ancient Greece',
                    'Ancient Rome',
                    'Achaemenid Empire',
                    'Gupta Empire',
                    'Han dynasty',
                    'Silk Road',
                    'Pre-Columbian era',
                    'Andean civilizations',
                    'Mesoamerica',
                    'Maya civilization']
    
    POST_CLASSICAL_HISTORY = ['Post-classical history ',
                            'Aztecs',
                            'Inca Empire',
                            'Islamic Golden Age',
                            'Middle Ages',
                            'Black Death',
                            'Byzantine Empire',
                            'Crusades',
                            'Holy Roman Empire',
                            'Viking Age',
                            'Mongol Empire',
                            'Ottoman Empire',
                            'Tang dynasty']
    
    MODERN_HISTORY = ['Early modern period',
                    'Renaissance',
                    'Age of Discovery',
                    'European colonization of the Americas',
                    'Western imperialism in Asia',
                    'Spanish Empire',
                    'Reformation',
                    'Mughal Empire',
                    'Scientific Revolution',
                    'Age of Enlightenment',
                    'Late modern period',
                    'British Empire',
                    'American Revolution',
                    'French Revolution',
                    'Industrial Revolution',
                    'Scramble for Africa',
                    'World War I',
                    'Soviet Union',
                    'Great Depression',
                    'World War II',
                    'Decolonization',
                    'Cold War',
                    'Green Revolution',
                    'Information Age']
    
    """
    GEOGRAPHY
    """
    
    GENERAL_GEOGRAPHY = ['Geography']
    
    CONTINENTS_AND_REGIONS = ['Continent',
                            'Africa',
                            'Antarctica',
                            'Asia',
                            'Europe ',
                            'North America ',
                            'South America ',
                            'Geographical regions',
                            'Arctic',
                            'Caribbean',
                            'Middle East',
                            'Oceania ']
    
    TERRESTIAL_FEATURES = ['Land ',
                        'Desert',
                        'Sahara',
                        'Forest',
                        'Amazon rainforest',
                        'Grassland',
                        'Island',
                        'Mountain',
                        'Alps',
                        'Andes',
                        'Himalayas',
                        'Rocky Mountains']
    
    HYDROLOGICAL_FEATURES = ['Sea ',
                            'Arctic Ocean',
                            'Atlantic Ocean',
                            'Mediterranean Sea',
                            'Indian Ocean',
                            'Pacific Ocean',
                            'Great Barrier Reef',
                            'Southern Ocean',
                            'Lake',
                            'Caspian Sea',
                            'Great Lakes',
                            'Lake Victoria',
                            'River',
                            'Amazon River',
                            'Ganges',
                            'Mississippi River',
                            'Nile',
                            'Yangtze',
                            'Glacier']
    
    COUNTRIES = ['Country ',
                'Africa',
                'Algeria',
                'Democratic Republic of the Congo',
                'Egypt',
                'Ethiopia',
                'Kenya',
                'Nigeria',
                'South Africa',
                'Tanzania',
                'Asia',
                'Bangladesh',
                'China',
                'India',
                'Indonesia',
                'Iran',
                'Israel',
                'Japan',
                'Malaysia',
                'Myanmar',
                'Pakistan',
                'Philippines',
                'Saudi Arabia',
                'South Korea',
                'Taiwan',
                'Thailand',
                'United Arab Emirates',
                'Vietnam',
                'Eurasia',
                'Russia',
                'Turkey',
                'Europe',
                'France',
                'Germany',
                'Italy',
                'Netherlands',
                'Poland',
                'Spain',
                'Ukraine',
                'United Kingdom',
                'North America',
                'Canada',
                'Mexico',
                'United States',
                'Oceania',
                'Australia',
                'South America',
                'Argentina',
                'Brazil',
                'Colombia']
    
    CITIES = ['City ',
            'Africa',
            'Cairo',
            'Lagos ',
            'Asia',
            'East Asia',
            'Beijing',
            'Hong Kong',
            'Tokyo',
            'Southeast Asia',
            'Jakarta',
            'Singapore',
            'India',
            'Delhi',
            'Mumbai',
            'Western Asia',
            'Istanbul',
            'Jerusalem',
            'Mecca',
            'Europe',
            'London',
            'Moscow',
            'Paris',
            'Rome',
            'North America',
            'Mexico City',
            'New York City',
            'South America',
            'São Paulo']
    
    """
    ARTS
    """
    
    GENERAL_ARTS = ['The arts ',
                    'Art',
                    'Prehistoric art',
                    'Fashion',
                    'Museum']
    
    ARTISTIC_MOVEMENTS = ['Abstract art',
                        'Modernism',
                        'Realism',
                        'Romanticism']
    
    ARCHITECTURE = ['Architecture ',
                    'Great Pyramid of Giza',
                    'Great Wall of China']
    
    LITERATURE = ['Literature ',
                'English literature',
                'Fiction',
                'Novel',
                'Short story',
                'Fairy tale',
                'Poetry',
                'Epic poetry']
    
    MUSIC = ['Music ',
            'Musical instrument',
            'Piano',
            'Singing',
            'Musical genres',
            'Classical music',
            'Folk music',
            'Jazz',
            'Pop music',
            'Rock music']
    
    PERFORMING_ARTS = ['Performing arts ',
                    'Dance',
                    'Opera',
                    'Orchestra',
                    'Theatre']
    
    VISUAL_ARTS = ['Visual arts ',
                'Film',
                'Animation',
                'Calligraphy',
                'Comics',
                'Design',
                'Drawing',
                'Painting',
                'Photography',
                'Pottery',
                'Sculpture']
    
    ARTS = GENERAL_ARTS + ARTISTIC_MOVEMENTS + ARCHITECTURE + LITERATURE + MUSIC + PERFORMING_ARTS + VISUAL_ARTS
    
    """
    PHILOSOPHY AND RELIGION
    """
    
    GENERAL_PHILOSOPHY = ['Philosophy ', 'Philosophy of science']
    
    PHILOSOPHICAL_BRANCHES_AND_CONCEPTS = ['Aesthetics',
                                        'Epistemology',
                                        'Knowledge ',
                                        'Belief',
                                        'Reason',
                                        'Truth',
                                        'Ethics ',
                                        'Good and evil',
                                        'Logic ',
                                        'Metaphysics',
                                        'Free will',
                                        'Ontology']
    
    PHILOSOPHY_BY_REGION_AND_PERIOD = ['Eastern philosophy',
                                        'Confucianism',
                                        'Western philosophy']
    
    MYTHOLOGY = ['Myth', 'Greek mythology']
    
    RELIGION = ['Religion ',
                'Afterlife',
                'Deity ',
                'God',
                'Meditation',
                'New religious movement',
                'Prayer',
                'Ritual',
                'Shamanism',
                'Soul',
                'Spirituality',
                'Secularism',
                'Atheism']
    
    """
    SPECIFIC RELIGIONS
    """
    
    ABRAHAMIC_RELIGIONS = ['Christianity',
                        'Bible',
                        'Catholic Church',
                        'Eastern Orthodox Church',
                        'Protestantism',
                        'Islam',
                        'Shia Islam',
                        'Sunni Islam',
                        'Quran',
                        'Judaism',
                        'Talmud']
    
    EAST_ASIAN_RELIGIONS = ['Chinese folk religion',
                            'Shinto',
                            'Taoism']
    
    INDIAN_RELIGIONS = ['Buddhism',
                        'Mahayana',
                        'Theravada',
                        'Hinduism',
                        'Vedas',
                        'Bhagavad Gita',
                        'Jainism',
                        'Sikhism']
    
    OTHER_RELIGIONS = ['Traditional African religions']
    
    """
    EVERYDAY LIFE
    """
    
    EVERYDAY_LIFE_GENERAL = ['Clothing ',
                            'Home ',
                            'Furniture',
                            'Jewellery']
    
    FAMILY_AND_KINSHIP = ['Ethnic group ',
                        'Family ',
                        'Adult',
                        'Adolescence',
                        'Child',
                        'Infant',
                        'Marriage',
                        'Old age',
                        'Parenting',
                        'Friendship']
    
    SEXUALITY_AND_GENDER = ['Human sexuality ',
                            'Sexual intercourse',
                            'Sexual orientation',
                            'Gender',
                            'Man',
                            'Woman']
    
    FOOD_AND_DRINK = ['Cooking',
                    'Food ',
                    'Bread',
                    'Cereal',
                    'Wheat',
                    'Maize',
                    'Rice',
                    'Cheese',
                    'Fruit',
                    'Meat',
                    'Salt',
                    'Spice',
                    'Sugar',
                    'Vegetable',
                    'Potato',
                    'Soybean',
                    'Drink',
                    'Alcoholic beverage',
                    'Coffee',
                    'Drinking water',
                    'Milk',
                    'Tea']
    
    RECREATION_AND_ENTERTAINMENT = ['Entertainment ',
                                    'Play ',
                                    'Game',
                                    'Board game',
                                    'Card game',
                                    'Gambling',
                                    'Video game',
                                    'Sport ',
                                    'Association football',
                                    'Sport of athletics',
                                    'Olympic Games',
                                    'Toy',
                                    'Martial arts',
                                    'Swimming',
                                    'Tourism'] 
    
    """
    SOCIETY AND SOCIAL SCIENCES
    """
    
    GENERAL_SOCIETY_AND_SOCIAL_SCIENCES = ['Culture ',
                                        'Folklore ',
                                        'Festival',
                                        'Oral tradition',
                                        'Popular culture',
                                        'Society ',
                                        'Community',
                                        'Power ',
                                        'Social class',
                                        'Communication ',
                                        'Social science',
                                        'Anthropology',
                                        'Sociology']
    
    POLITICS_AND_GOVERNMENT = ['Politics ',
                            'Political party',
                            'Political science',
                            'Colonialism',
                            'Imperialism',
                            'Government ',
                            'Democracy',
                            'Dictatorship',
                            'Monarchy',
                            'Ideology',
                            'Anarchism',
                            'Capitalism',
                            'Communism',
                            'Conservatism',
                            'Fascism',
                            'Liberalism',
                            'Nationalism',
                            'Socialism',
                            'State |State',
                            'Diplomacy',
                            'Military',
                            'International organizations',
                            'European Union',
                            'International Red Cross and Red Crescent Movement',
                            'NATO',
                            'United Nations']
    
    CONFLICT = ['War ',
                'Genocide',
                'Peace',
                'Terrorism']
    
    EDUCATION = ['Education ',
                'School',
                'Library',
                'University']
    
    BUSINESS = ['Business ',
                'Corporation',
                'Management',
                'Marketing',
                'Retail',
                'Trade union',
                'Economics ',
                'Trade ',
                'Supply and demand',
                'Employment',
                'Finance',
                'Bank',
                'Money',
                'Insurance',
                'Tax',
                'Economy',
                'Agriculture ',
                'Manufacturing ',
                'Construction',
                'Fishing',
                'Hunting',
                'Mining']
    
    SOCIAL_ISSUES = ['Abortion',
                    'Disability',
                    'Discrimination',
                    'Racism',
                    'Sexism',
                    'Environmentalism',
                    'Pollution',
                    'Famine',
                    'Feminism',
                    'Globalization',
                    'Human migration',
                    'Human rights',
                    'Liberty',
                    'Privacy',
                    'Slavery',
                    'Social equality',
                    'Suffrage',
                    'Indigenous peoples',
                    'Poverty',
                    'Violence',
                    'Welfare']
    
    LAW = ['Law ',
        'Crime',
        'Constitution',
        'Justice',
        'Police',
        'Property']
    
    PSYCHOLOGY = ['Psychology ',
                'Emotion ',
                'Anger',
                'Fear',
                'Happiness',
                'Humour',
                'Love',
                'Mind ',
                'Consciousness',
                'Dream',
                'Memory',
                'Thought',
                'Human behavior',
                'Intelligence',
                'Learning',
                'Personality']
    
    LANGUAGE = ['Language ',
                'Indo-European languages',
                'Bengali language|Bengali',
                'English language|English',
                'French language|French',
                'German language|German',
                'Greek language|Greek',
                'Hindustani language|Hindustani',
                'Latin',
                'Portuguese language|Portuguese',
                'Russian language|Russian',
                'Spanish language|Spanish',
                'Other languages',
                'Arabic',
                'Chinese language|Chinese',
                'Japanese language|Japanese',
                'Malay language|Malay',
                'Swahili language|Swahili',
                'Linguistics',
                'Grammar',
                'Word',
                'Personal name',
                'Speech',
                'Writing ',
                'Alphabet',
                'Arabic script',
                'Brahmic scripts',
                'Cyrillic script',
                'Greek alphabet',
                'Latin script',
                'Arabic numerals',
                'Chinese characters']
    
    MEDIA = ['Mass media ',
            'Broadcasting',
            'News',
            'Publishing']
    
    """
    HEALTH MEDICINE AND DISEASE
    """
    
    ILLNESS_AND_INJURY = ['Disease ',
                        'Allergy',
                        'Asthma',
                        'Cancer',
                        'Cardiovascular disease',
                        'Stroke',
                        'Diabetes',
                        'Gastroenteritis',
                        'Infection',
                        'Common cold',
                        'Influenza',
                        'Malaria',
                        'Pneumonia',
                        'Sexually transmitted infection',
                        'HIV/AIDS',
                        'Smallpox',
                        'Tuberculosis',
                        'Mental disorder',
                        'Injury']
    
    HEALTH_FITNESS_AND_MEDICINE = ['Medicine ',
                                'Dentistry',
                                'Hospital',
                                'Nursing',
                                'Surgery',
                                'Ageing',
                                'Exercise',
                                'Health',
                                'Mental health',
                                'Hygiene',
                                'Sanitation',
                                'Nutrition',
                                'Obesity']
    
    DRUGS_AND_MEDICATION = ['Drug',
                            'Medication',
                            'Anesthesia',
                            'Antibiotic',
                            'Birth control',
                            'Vaccine',
                            'Addiction',
                            'Alcoholism',
                            'Smoking']
    
    """
    SCIENCE
    """
    
    GENERAL_SCIENCE = ['Science ',
                    'Scientific method',
                    'Measurement',
                    'International System of Units',
                    'Nature']
    
    ASTRONOMY = ['Astronomy ',
                'Universe ',
                'Solar System ',
                'Sun ',
                'Mercury |Mercury',
                'Venus',
                'Earth ',
                'Moon ',
                'Mars',
                'Jupiter',
                'Saturn',
                'Uranus',
                'Neptune',
                'Asteroid',
                'Big Bang',
                'Black hole',
                'Comet',
                'Galaxy',
                'Milky Way',
                'Natural satellite',
                'Orbit',
                'Outer space',
                'Physical cosmology',
                'Planet',
                'Star',
                'Supernova']
    
    PHYSICS = ['Physics ',
            'Energy ',
            'Time ',
            'Day',
            'Year',
            'Classical mechanics',
            'Mass',
            'Momentum',
            'Motion',
            'Newtons laws of motion',
            'Force',
            'Electromagnetism',
            'Gravity',
            'Strong interaction',
            'Weak interaction',
            'Magnetism',
            'Matter',
            'State of matter',
            'Atom ',
            'Particle physics',
            'Standard Model',
            'Subatomic particle',
            'Electron',
            'Neutron',
            'Photon',
            'Proton',
            'Quantum mechanics',
            'Radioactive decay',
            'Space',
            'Vacuum',
            'Thermodynamics',
            'Heat',
            'Temperature',
            'Theory of relativity',
            'Speed of light',
            'Wave',
            'Electromagnetic radiation',
            'Light',
            'Color',
            'Optics',
            'Sound']
    
    BIOLOGY = ['Biology ',
            'Life ',
            'Cell |Cell ',
            'Death ',
            'Suicide',
            'Abiogenesis',
            'Evolution ',
            'Human evolution',
            'Natural selection',
            'Organism',
            'Archaea',
            'Bacteria',
            'Eukaryote',
            'Animal ',
            'Zoology',
            'Amphibian',
            'Arthropod',
            'Crustacean',
            'Insect',
            'Bird',
            'Chicken',
            'Fish',
            'Mammal',
            'Cat',
            'Cattle',
            'Dog',
            'Horse',
            'Pig',
            'Primate',
            'Human ',
            'Rodent',
            'Sheep',
            'Mollusca',
            'Reptile',
            'Dinosaur',
            'Plant ',
            'Algae',
            'Botany',
            'Flower',
            'Seed',
            'Tree',
            'Fungus',
            'Virus',
            'Anatomy ',
            'Human body',
            'Circulatory system',
            'Blood',
            'Heart',
            'Lung',
            'Digestion',
            'Liver',
            'Immune system',
            'Skeletal muscle',
            'Nervous system',
            'Brain',
            'Ear',
            'Eye',
            'Sense',
            'Skeleton',
            'Bone',
            'Skin',
            'Ecology ',
            'Biodiversity',
            'Ecosystem',
            'Extinction',
            'Genetics',
            'DNA',
            'Gene',
            'Heredity',
            'RNA',
            'Metabolism',
            'Molecular biology',
            'Hormone',
            'Protein',
            'Paleontology',
            'Photosynthesis',
            'Reproduction',
            'Sex',
            'Pregnancy',
            'Sleep',
            'Taxonomy',
            'Species']
    
    CHEMISTRY = ['Chemistry ',
                'Biochemistry',
                'Inorganic chemistry',
                'Organic chemistry',
                'Physical chemistry',
                'Chemical element ',
                'Periodic table',
                'Aluminium',
                'Carbon',
                'Copper',
                'Gold',
                'Hydrogen',
                'Iron',
                'Nitrogen',
                'Oxygen',
                'Phosphorus',
                'Silicon',
                'Silver',
                'Sulfur',
                'Chemical compound',
                'Water ',
                'Carbon dioxide',
                'Chemical bond',
                'Molecule',
                'Chemical reaction',
                'Acid–base reaction',
                'Catalysis',
                'Redox',
                'Metal',
                'Alloy',
                'Bronze',
                'Steel']
    
    EARTH_SCIENCE = ['Earth science',
                    'History of Earth',
                    'Atmosphere of Earth',
                    'Internal structure of Earth',
                    'Season',
                    'Flood',
                    'Climate ',
                    'Climate change',
                    'Weather',
                    'Cloud',
                    'Rain',
                    'Snow',
                    'Tornado',
                    'Tropical cyclone',
                    'Wind',
                    'Geology ',
                    'Earthquake',
                    'Erosion',
                    'Mineral',
                    'Plate tectonics',
                    'Rock |Rock',
                    'Soil',
                    'Volcano']
    
    """
    TECHNOLOGY
    """
    
    GENERAL_TECHNOLOGY = ['Technology ',
                        'Engineering ',
                        'Civil engineering',
                        'Mechanical engineering']
    
    ENERGY = ['Electricity ',
            'Electric battery',
            'Fire ',
            'Explosive',
            'Gunpowder',
            'Fossil fuel',
            'Coal',
            'Natural gas',
            'Petroleum',
            'Nuclear power',
            'Renewable energy',
            'Hydropower',
            'Solar energy',
            'Wind power']
    
    FOOD_AND_HEALTH = ['Animal husbandry',
                    'Domestication',
                    'Biotechnology',
                    'Genetic engineering',
                    'Fertilizer',
                    'Food preservation',
                    'Garden',
                    'Medical imaging',
                    'Refrigeration',
                    'Stove']
    
    WEAPONS = ['Weapon',
            'Armour',
            'Bow and arrow',
            'Firearm',
            'Knife',
            'Nuclear weapon']
    
    TOOLS_AND_MACHINERY = ['Tool ',
                        'Simple machine',
                        'Wheel',
                        'Engine',
                        'Electric motor',
                        'Internal combustion engine',
                        'Jet engine',
                        'Steam engine',
                        'Robotics']
    
    MEDIA_AND_COMMUNICATION = ['Printing',
                            'Book ',
                            'Mail',
                            'Telecommunications',
                            'Internet',
                            'Radio',
                            'Telephone',
                            'Mobile phone',
                            'Video',
                            'Television']
    
    COMPUTING_AND_INFORMATION_TECHNOLOGY = ['Computer science',
                                            'Computer ',
                                            'Artificial intelligence',
                                            'Cryptography']
    
    ELECTRONICS = ['Electronics',
                'Electric light',
                'Integrated circuit',
                'Semiconductor device']
    
    SPACE = ['Rocket',
            'Satellite',
            'Space exploration',
            'Spaceflight',
            'Space station']
    
    TRANSPORTATION = ['Transport ',
                    'Aircraft',
                    'Bicycle',
                    'Car',
                    'Rail transport',
                    'Ship']
    
    NAVIGATION_AND_TIMEKEEPING = ['Navigation',
                                'Compass',
                                'Map',
                                'Radar',
                                'Calendar',
                                'Clock']
    
    STRUCTURES = ['Fortification',
                'Infrastructure',
                'Bridge',
                'Canal',
                'Dam',
                'Road']
    
    MATERIALS = ['Concrete',
                'Glass',
                'Masonry',
                'Metallurgy',
                'Natural rubber',
                'Paper',
                'Plastic',
                'Textile',
                'Cotton',
                'Wood']
    
    OPTICAL = ['Camera',
            'Laser',
            'Lens',
            'Microscope',
            'Telescope']
    
    """
    MATHEMATICS 
    """
    
    GENERAL_MATHEMATICS = ['Mathematics ',
                        'Algorithm',
                        'Mathematical proof',
                        'Set |Set',
                        'Function |Function']
    
    COUNTING_AND_NUMBERS = ['Combinatorics',
                            'Number ',
                            'Real number',
                            'E | ',
                            'Pi| ',
                            'Fraction',
                            'Integer',
                            '0',
                            'Natural number',
                            'Prime number',
                            'Complex number',
                            'Number theory']
    
    ALGEBRA = ['Algebra',
            'Equation',
            'Variable |Variable',
            'Linear algebra',
            'Abstract algebra']
    
    ANALYSIS = ['Mathematical analysis',
                'Calculus',
                'Infinity',
                'Limit |Limit',
                'Series |Series']
    
    ARITHMETIC = ['Arithmetic ',
                'Exponentiation',
                'Logarithm',
                'Nth root|nth root']
    
    GEOMETRY_AND_TOPOLOGY = ['Geometry ',
                            'Angle',
                            'Trigonometry',
                            'Area',
                            'Conic section',
                            'Circle',
                            'Line |Line',
                            'Polygon',
                            'Triangle',
                            'Three-dimensional space',
                            'Volume',
                            'Topology']
    
    PROBABILITY_AND_STATISTICS = ['Probability',
                                'Statistics ']

if __name__ == "__main__":
    
    ...